---
version: "3.5"
services: 
  jenkins:
    build: jenkins-setup
    ports:
    - 8080:8080
    volumes:
    - /etc/sysconfig/docker:/etc/sysconfig/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /home/vagrant/docker-python-ci/jenkins-jobs/:/var/jenkins_home/jobs/:Z
  registry:
    image: registry
    ports:
    - 5000:5000
...
